vs_borica_prepare:
    path:     /borica/prepare
    controller: Vankosoft\BoricaBundle\Controller\BoricaController::prepareAction
    options:
        expose: true

vs_borica_done:
    path:     /borica/done
    controller: Vankosoft\BoricaBundle\Controller\BoricaController::doneAction
