services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    Vankosoft\BoricaBundle\Controller\BoricaController:
        arguments:
            - '@event_dispatcher'
            - '@translator'
            - '@doctrine'
            - '@payum'
            - '@vs_users.security_bridge'
            - '@vs_payment_payment'
            - '@vs_payment.order_factory'
            - '@vs_payment.pricing_plan_subscriptions_bridge'
            - '%vs_payment.model.payment.class%'
            - '%vs_payment.checkout.throw_exception_on_payment_done%'
            - '%vs_payment.shopping_cart_redirect_on_payment_done%'
            - '%vs_payment.pricing_plans_redirect_on_payment_done%'
            - '%vs_payment.subscription_redirect_on_payment_done%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
